### ISSUE TITLE
Issue migrating from NPM

### ISSUE THREAD

**Issue by valterbarreira** [openappsec/open-appsec-npm#24]
I have NPM 2.11.3 and i followed the guide how to migrate and keep configuration from here [https://docs.openappsec.io/troubleshooting/troubleshooting-guides/how-to-migrate-from-an-existing-nginx-proxy-manager-deployment-and-keep-configuration](url) but the configuration wasn't kept. In openappsec yaml doesn't mention db and in my npm yaml i have a db declaration. Here's my NPM yaml config
 
```
version: "3.8"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
    environment:
      # These are the settings to access your db
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # If you would rather use Sqlite uncomment this
      # and remove all DB_MYSQL_* lines above
      # DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: jc21/mariadb-aria:10.4.15-innodb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./config.json:/home/nginx/nginxmanager/config.json

```
