### ISSUE TITLE
open-appsec only lears

### ISSUE THREAD

**Issue by stathismes** [openappsec/open-appsec-npm#32]
I'm using nginx proxy manager integrated with the open appsec but what i can see all the attempts aren't getting blocked by open appsec, the security action only on detect state and not block even i already change the enforcement mode to prevent-learn. Refer screenshot below. What can I change to make the WAF block on any security attempt.

![image](https://github.com/user-attachments/assets/c5610c23-e7c0-48af-9ef5-5d8b00e5e057)

**Comment by orianelou** [comment]
Hi @stathismes, 

Can you please attach the following:
1. Docker Compose being used
2. NGINX Proxy Manager host configuration
3. open-appsec local policy (can be copied from NGINX Proxy Manager advanced tab).

Best,

the open-appsec team

**Comment by stathismes** [comment]
1) My docker compose YAML:


```
services:
  appsec-npm:
    container_name: npm-attachment
    image: 'ghcr.io/openappsec/nginx-proxy-manager-attachment:latest'
    ipc: host
    network_mode: "host"
    volumes:
      - /opt/nginxproxymanager/data:/data
      - /opt/nginxproxymanager/letsencrypt:/etc/letsencrypt
      - /opt/nginxproxymanager/data/nginx/_hsts.conf:/app/templates/_hsts.conf:ro
      - /opt/nginxproxymanager/data/nginx/_hsts_map.conf:/app/templates/_hsts_map.conf:ro
      - /opt/nginxproxymanager/data/nginx/custom/http_top.conf:/data/nginx/custom/http_top.conf:rw
      - /opt/nginxproxymanager/appsec-logs:/ext/appsec-logs
      - /opt/nginxproxymanager/appsec-localconfig:/ext/appsec
    environment:
      TZ: Europe/Athens
      DISABLE_IPV6: 'true'
      #X_FRAME_OPTIONS: "sameorigin" # I have set this in _hsts.conf. Check https://geekscircuit.com/nginx-proxy-manager/#docker-cli
    restart: always
  appsec-agent:
    container_name: appsec-agent
    image: 'ghcr.io/openappsec/agent:latest'
    network_mode: service:appsec-npm
    ipc: host
    environment:
      # adjust with your own email below
      - user_email=xxxxxxx@xxxxxxx.com
      - nginxproxymanager=true
      - autoPolicyLoad=true
    volumes:
      - /opt/nginxproxymanager/appsec-config:/etc/cp/conf
      - /opt/nginxproxymanager/appsec-data:/etc/cp/data
      - /opt/nginxproxymanager/appsec-logs:/var/log/nano_agent
      - /opt/nginxproxymanager/appsec-localconfig:/ext/appsec
      - /opt/nginxproxymanager/open-appsec-advance-model/open-appsec-advanced-model.tgz:/advanced-model/open-appsec-advanced-model.tgz:rw
    command: /cp-nano-agent --standalone
    restart: always

```


2) one internal host portal inside my network

![image](https://github.com/user-attachments/assets/8369adff-3731-404d-b87d-6b886543917f)

![image](https://github.com/user-attachments/assets/da108178-f220-4cd9-9713-180c86035e0c)



3) The policy file looks for above host only like below:


```

policies:
  default:
    triggers:
      - appsec-default-log-trigger
    mode: inactive
    practices:
      - webapp-default-practice
    custom-response: appsec-default-web-user-response
  specific-rules:

    - host: download.xxxxxxxxxxx.xxx
      name: npm-managed-specific-rule-proxyhost-5
      triggers:
        - npm-managed-log-trigger-proxyhost-5
      mode: prevent-learn
      practices:
        - npm-managed-practice-proxyhost-5
//
//
//
//
practices:
  - name: webapp-default-practice
    web-attacks:
      max-body-size-kb: 1000000
      max-header-size-bytes: 102400
      max-object-depth: 40
      max-url-size-bytes: 32768
      minimum-confidence: high
      override-mode: inactive
      protections:
        csrf-protection: inactive
        error-disclosure: inactive
        non-valid-http-methods: false
        open-redirect: inactive
    anti-bot:
      injected-URIs: []
      validated-URIs: []
      override-mode: inactive
    snort-signatures:
      configmap: []
      override-mode: inactive
    openapi-schema-validation:
      configmap: []
      override-mode: inactive
//
//
//
//	  
  - name: npm-managed-practice-proxyhost-5
    web-attacks:
      max-body-size-kb: 1000000
      max-header-size-bytes: 102400
      max-object-depth: 40
      max-url-size-bytes: 32768
      minimum-confidence: high
      override-mode: prevent-learn
      protections:
        csrf-protection: inactive
        error-disclosure: inactive
        non-valid-http-methods: false
        open-redirect: inactive
    anti-bot:
      injected-URIs: []
      validated-URIs: []
      override-mode: inactive
    snort-signatures:
      configmap: []
      override-mode: inactive
    openapi-schema-validation:
      configmap: []
      override-mode: inactive
//
//
//
//	
  - name: npm-managed-log-trigger-proxyhost-5
    access-control-logging:
      allow-events: false
      drop-events: true
    additional-suspicious-events-logging:
      enabled: true
      minimum-severity: high
      response-body: false
      response-code: true
    appsec-logging:
      all-web-requests: false
      detect-events: true
      prevent-events: true
    extended-logging:
      http-headers: false
      request-body: false
      url-path: true
      url-query: true
    log-destination:
      cloud: false
      stdout:
        format: json
//
//
//
//	
custom-responses:
  - name: appsec-default-web-user-response
    mode: response-code-only
    http-response-code: 403

```

Originally I used the sample/default policy posted in the instructions: [initial declarative configuration file](https://raw.githubusercontent.com/openappsec/open-appsec-npm/main/deployment/local_policy.yaml). After playing around my Hosts configurations and changing the open-appsec settings, of course this file was changing every time, and now includes all my hosts and info.
