### ISSUE TITLE
NPM + OpenAppSec + Crowdsec(Docker Compose) are working?

### ISSUE THREAD

**Issue by Caio2a7** [openappsec/open-appsec-npm#46]
Hello, I have a question about if it is possible to fully integrate NPM, OpenAppsec and Crowdsec. I did this in my docker-compose that I will provide below. The integration initially seems to work, the events generated by Appsec are loaded by crowdsec and this makes it generate alerts and decisions normally:

![Image](https://github.com/user-attachments/assets/0fec23a6-94fe-469f-885c-9cb3ea5cf7b3)

However, the problem is that crowdsec ban decisions are not applied by openappsec, so the malicious IP can make requests normally. I am using v1beta1 local_policy.yaml file.

And The following OpenAppsec log files are completely empty: cp-nano-crowdsec-aux.log, cp-nano-crowdsec-aux.err, cp-nano-
crowdsec-aux.dbg

The agent status: 
![Image](https://github.com/user-attachments/assets/703def51-e410-4c77-b49e-5d116fc9c4ee)

My docker-compose.yaml:

```yaml
version: '3.9'

services:
  appsec-agent:
    image: ghcr.io/openappsec/agent:${APPSEC_VERSION}
    container_name: appsec-agent
    network_mode: service:appsec-npm  # Compartilha a rede com appsec-npm
    ipc: host                         # Compartilha memória IPC como esperado pelo appsec
    restart: unless-stopped
    environment:
      - SHARED_STORAGE_HOST=appsec-shared-storage
      - LEARNING_HOST=appsec-smartsync
      - TUNING_HOST=appsec-tuning-svc
      - user_email=${APPSEC_USER_EMAIL}
      - autoPolicyLoad=${APPSEC_AUTO_POLICY_LOAD}
      - nginxproxymanager=true
      - CROWDSEC_ENABLED=true
      - CROWDSEC_MODE=prevent
      - CROWDSEC_LOGGING=enabled
      - CROWDSEC_API_URL=http://crowdsec:8080/v1/decisions
      - CROWDSEC_AUTH_METHOD=apikey
      - CROWDSEC_AUTH_DATA=[mykey]
      - DEBUG_LEVEL=debug
    volumes:
      - ./schemas:/etc/openappsec/schemas
      - ./snort:/etc/snort/rules
      - ${APPSEC_CONFIG}:/etc/cp/conf
      - ${APPSEC_DATA}:/etc/cp/data
      - ${APPSEC_LOGS}:/var/log/nano_agent
      - ${APPSEC_LOCALCONFIG}:/ext/appsec
      - ./crowdsecAux.config:/etc/cp/crowdsecAux/crowdsecAux.config
    command: /cp-nano-agent --standalone

  appsec-npm:
    container_name: appsec-npm
    image: ghcr.io/openappsec/nginx-proxy-manager-attachment:${APPSEC_VERSION}
    ipc: host
    restart: unless-stopped
    ports:
      - 80:80 
      - 443:443
      - 81:81 
    volumes:
      - ${NPM_DATA}:/data
      - ${NPM_LETSENCRYPT}:/etc/letsencrypt
      - ${APPSEC_LOGS}:/ext/appsec-logs
      - ${APPSEC_LOCALCONFIG}:/ext/appsec

  appsec-smartsync:
    profiles:
      - standalone
    image: ghcr.io/openappsec/smartsync:${APPSEC_VERSION}
    container_name: appsec-smartsync
    environment:
      - SHARED_STORAGE_HOST=appsec-shared-storage
    restart: unless-stopped
    depends_on:
      - appsec-shared-storage

  appsec-shared-storage:
    profiles:
      - standalone
    image: ghcr.io/openappsec/smartsync-shared-files:${APPSEC_VERSION}
    container_name: appsec-shared-storage
    ipc: host
    restart: unless-stopped
    user: root
    volumes:
      - ${APPSEC_SMART_SYNC_STORAGE}:/db:z
#     - learning_nfs:/db:z

  appsec-db:
    profiles:
      - standalone
    image: postgres
    container_name: appsec-db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${APPSEC_DB_PASSWORD}
      - POSTGRES_USER=${APPSEC_DB_USER} 
    volumes:
      - ${APPSEC_POSTGRES_STORAGE}:/var/lib/postgresql/data

  appsec-tuning-svc:
    profiles:
      - standalone
    image: ghcr.io/openappsec/smartsync-tuning:${APPSEC_VERSION}
    container_name: appsec-tuning-svc
    environment:
      - SHARED_STORAGE_HOST=appsec-shared-storage
      - QUERY_DB_PASSWORD=${APPSEC_DB_PASSWORD}
      - QUERY_DB_HOST=${APPSEC_DB_HOST}
      - QUERY_DB_USER=${APPSEC_DB_USER}
    restart: unless-stopped
    volumes:
      - ${APPSEC_CONFIG}:/etc/cp/conf
    depends_on:
      - appsec-shared-storage
      - appsec-db

  crowdsec:
    image: crowdsecurity/crowdsec:${APPSEC_VERSION}
    container_name: crowdsec
    restart: unless-stopped
    volumes:
      - ./crowdsec-config:/etc/crowdsec
      - ./crowdsec-db:/var/lib/crowdsec/data
      - ${APPSEC_LOGS}:/logs/openappsec:ro
    environment:
      - COLLECTIONS=openappsec/openappsec
      - BOUNCER_KEY_openappsec=[mykey]
      - DISABLE_PARSERS=crowdsecurity/whitelists
    ports:
      - 8080:8080
 ```

I would appreciate any help.
