### ISSUE TITLE
Failed to Signal Nano Service & Failed to Register to Attachments Manager Service

### ISSUE THREAD

**Issue by jiriteach** [openappsec/open-appsec-npm#47]
Hi - I am using the NPMplus implementation with open-appsec but thought I would post this here given these errors are from open-appsec. I noticed my proxy hosts not accessible before - checked the NPMplus container and it was in an "unhealthy" state with these errors. Has been working fine for days.

Restart of the container fixed it but any reason what could have caused this? This is the NPMplus container. The agent container looked fine and didnt require a restart.

Thanks

```
{"log":"|2025-05-07T04:43:57.348: ngx_http_cp_signal_to_service@ngx_cp_io.c:67 [uid 2 | pid 29574] \u003csession id 155\u003e | Failed to signal nano service, trying to restart communications\n","stream":"stderr","time":"2025-05-06T16:43:57.829913971Z"}
{"log":"|2025-05-07T04:43:57.348: ngx_cp_attachment_init_process@ngx_cp_initializer.c:631 [uid 2 | pid 29574] \u003csession id 157\u003e | Failed to register to Attachments Manager service\n","stream":"stderr","time":"2025-05-06T16:43:57.830080661Z"}
{"log":"|2025-05-07T04:43:57.366: ngx_http_cp_signal_to_service@ngx_cp_io.c:67 [uid 3 | pid 29599] \u003csession id 91\u003e | Failed to signal nano service, trying to restart communications\n","stream":"stderr","time":"2025-05-06T16:43:57.848311901Z"}
{"log":"|2025-05-07T04:43:57.367: ngx_cp_attachment_init_process@ngx_cp_initializer.c:631 [uid 3 | pid 29599] \u003csession id 93\u003e | Failed to register to Attachments Manager service\n","stream":"stderr","time":"2025-05-06T16:43:57.848407444Z"}
{"log":"|2025-05-07T04:43:59.622: ngx_cp_attachment_init_process@ngx_cp_initializer.c:631 [uid 3 | pid 29599] \u003csession id 95\u003e | Failed to register to Attachments Manager service\n","stream":"stderr","time":"2025-05-06T16:43:59.107382694Z"}
{"log":"|2025-05-07T04:44:00.537: ngx_http_cp_signal_to_service@ngx_cp_io.c:67 [uid 6 | pid 29703] \u003csession id 55\u003e | Failed to signal nano service, trying to restart communications\n","stream":"stderr","time":"2025-05-06T16:44:00.021590938Z"}
{"log":"|2025-05-07T04:44:03.849: ngx_cp_attachment_init_process@ngx_cp_initializer.c:631 [uid 3 | pid 29599] \u003csession id 109\u003e | Failed to register to Attachments Manager service\n","stream":"stderr","time":"2025-05-06T16:44:03.331086249Z"}
{"log":"|2025-05-07T04:44:06.954: ngx_cp_attachment_init_process@ngx_cp_initializer.c:631 [uid 3 | pid 29599] \u003csession id 123\u003e | Failed to register to Attachments Manager service\n","stream":"stderr","time":"2025-05-06T16:44:06.436084336Z"}
{"log":"|2025-05-07T04:44:06.075: ngx_cp_attachment_init_process@ngx_cp_initializer.c:631 [uid 3 | pid 29599] \u003csession id 137\u003e | Failed to register to Attachments Manager service\n","stream":"stderr","time":"2025-05-06T16:44:06.557077227Z"
```

**Comment by jiriteach** [comment]
Closing for now as found a thread on the NPMplus GH issues similar to this - https://github.com/ZoeyVid/NPMplus/issues/1651

**Comment by jiriteach** [comment]
NPMplus advised that it would be best to raise this issue here - https://github.com/ZoeyVid/NPMplus/issues/1781

**Comment by jiriteach** [comment]
Sure - Here you go - 

```
services:
  npmplus:
    container_name: npm-plus
    image: docker.io/zoeyvid/npmplus:latest
    restart: always
  
    ipc: service:openappsec-agent

    volumes:
      - "/home/administrator/Docker/npm-plus/data:/data"
      - "/home/administrator/Docker/npm-plus/letsencrypt:/etc/letsencrypt"
      - "/var/www:/var/www"
      - "/etc/nginx/databases:/other/databases"
      
    ports:
      - "80:80"
      - "443:443"
      - 
      - "9002:81"
      - "9003:91"

    environment:
      - "TZ=Pacific/Auckland"
      
      - "ACME_EMAIL=xxx@xxx.xxx.xxx"

      - "NGINX_LOG_NOT_FOUND=true"
      
      - "LOGROTATE=true"
      - "LOGROTATIONS=5"
      - "GOA=true"

      - "NGINX_LOAD_OPENAPPSEC_ATTACHMENT_MODULE=true"
      - "NGINX_LOAD_GEOIP2_MODULE=true"
      
  openappsec-agent:
    container_name: npm-oas
    image: ghcr.io/openappsec/agent:latest
    restart: always
    ipc: shareable
    volumes:
      - "/home/administrator/Docker/npm-plus/oas/conf:/etc/cp/conf"
      - "/home/administrator/Docker/npm-plus/oas/data:/etc/cp/data"
      - "/home/administrator/Docker/npm-plus/oas/logs:/var/log/nano_agent"
      - "/home/administrator/Docker/npm-plus/oas/model/open-appsec-advanced-model.tgz:/advanced-model/open-appsec-advanced-model.tgz"
    environment:
      - "TZ=Pacific/Auckland"
      - "autoPolicyLoad=true"
      - "registered_server=NPMplus"
      - "user_email=xxx@xxx.xxx.xxx"
      - "AGENT_TOKEN="
    command: /cp-nano-agent
```
